language: python

#
# Test test matrix is spelled out explicitly here.
#
# For each supported version of Python, we will test with coverage.
#
matrix:
  include:
  - python: 3.6
    env: TOXENV=pep8,pylint
  - python: 3.6
    env: TOXENV=docs

  - python: 3.4
    env: TOXENV=py34,codecov
  - python: 3.5
    env: TOXENV=py35,codecov
  - python: 3.6
    env: TOXENV=py36,codecov
  - python: 3.7
    env: TOXENV=py37,codecov
    # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
    dist: xenial
    sudo: required

  # Failures on these unsupported python versions are allowed
  allow_failures:
  - env: TOXENV=py35,codecov
  - env: TOXENV=py37,codecov

install:
- pip install tox

script:
- tox -vvv

notifications:
  email: false
