---
- hosts: controller
  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{aws_config | default('config/aws.yml')}}"
        - "config/treadmill.yml"

- include: instance.yml _name="{{freeipa.name}}" _exact_count="{{freeipa.exact_count}}" _instance_type="{{freeipa.instance_type}}"

- hosts: controller
  roles:
    - {role: route53-freeipa-server}

- hosts: ec2instances
  become: yes
  environment:
    AWS_ACCESS_KEY_ID: "{{hostvars.localhost.ansible_env.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "{{hostvars.localhost.ansible_env.AWS_SECRET_ACCESS_KEY}}"
  vars_files:
    - "{{aws_config | default('config/aws.yml')}}"
    - "config/treadmill.yml"
  roles:
    - {role: freeipa-server}
