---
- hosts: controller
  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{aws_config | default('config/aws.yml')}}"
        - "config/treadmill.yml"

- include: instance.yml _name="{{node_server.name}}" _exact_count="{{node_server.exact_count}}" _instance_type="{{node_server.instance_type}}"

- hosts: ec2instances
  environment:
    AWS_ACCESS_KEY_ID: "{{hostvars.localhost.ansible_env.AWS_ACCESS_KEY_ID}}"
    AWS_SECRET_ACCESS_KEY: "{{hostvars.localhost.ansible_env.AWS_SECRET_ACCESS_KEY}}"
  vars_files:
    - "{{aws_config | default('config/aws.yml')}}"
    - "config/treadmill.yml"
  become: yes
  roles:
    - {role: node-server}
