memory: 1G
cpu: 20%
disk: 1G
services:
- command: |
    exec treadmill sproc restapi -p 5108 \
      --title 'Treadmill_Global_Config_API' \
      -m app,app-group,app-dns,tenant,lbendpoint,allocation,cell \
      --cors-origin='.*'
  name: rest-api
  restart:
    limit: 5
    interval: 60
endpoints:
- name: http
  port: 5108
  type: infra
environ:
- name: KRB5CCNAME
  value: /etc/tickets/treadmld
