galaxy_info:
  author: your name
  description: your description
  company: your company (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: []

dependencies:
  - { role: fetch-facts, resources: ['freeipa_facts','master_facts','node_facts','subnet','vpc','route_table']}
